'version': '3.10'

services:
  database:
    image: postgres:15.2
    container_name: web_database
    volumes:
      - database_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./server/.env
    ports:
      - '5433:5432'
  web:
    build:
      context: ./
    container_name: web_app
    command: bash -c 'python /home/app/server/manage.py migrate --noinput && python /home/app/server/manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./server/:/home/app/server
    depends_on:
      - database
    ports:
      - 8000:8000
    env_file:
      - ./server/.env

volumes:
  database_data:
