# Generated by Django 4.2.1 on 2023-06-20 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чатов'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната чата', 'verbose_name_plural': 'Комнаты чатов'},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=512, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='online',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Online'),
        ),
    ]
